project:
  type: website

website:
  google-analytics: "G-DBRES1DZDQ"
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - text: Projects
        menu:
          - href: breast_cancer_prediction.qmd
            text: Breast Cancer Prediction
      - href: https://www.linkedin.com/in/aaron-morris-201517/
        text: Linkedin
      - href: https://github.com/aarontmo?tab=repositories
        text: Github

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    code-fold: true
    engine: jupyter
    author: Aaron Morris



